spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/clear_the_fridge?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

